/**
 * 诗词名句列表：展示千古传诵的名句及其出处
 */
export const records = [
  {
    title: '清平乐·画堂晨起',
    dynasty: '唐',
    author: '李白',
    digest: '应是天仙狂醉，乱把白云揉碎。',
  },
  {
    title: '上李邕',
    dynasty: '唐',
    author: '李白',
    digest: '大鹏一日同风起，扶摇直上九万里。',
  },
  {
    title: '南陵别儿童入京',
    dynasty: '唐',
    author: '李白',
    digest: '仰天大笑出门去，我辈岂是蓬蒿人。',
  },
  {
    title: '将进酒',
    dynasty: '唐',
    author: '李白',
    digest: '天生我材必有用，千金散尽还复来。',
  },
  {
    title: '侠客行',
    dynasty: '唐',
    author: '李白',
    digest: '事了拂衣去，深藏身与名。',
  },
  {
    title: '梦游天姥吟留别',
    dynasty: '唐',
    author: '李白',
    digest: '安能摧眉折腰事权贵，使我不得开心颜？',
  },
  {
    title: '冬夜读书示子聿',
    dynasty: '宋',
    author: '陆游',
    digest: '纸上得来终觉浅，绝知此事要躬行。',
  },
  {
    title: '游山西村',
    dynasty: '宋',
    author: '陆游',
    digest: '山重水复疑无路，柳暗花明又一村。',
  },
  {
    title: '示儿',
    dynasty: '宋',
    author: '陆游',
    digest: '王师北定中原日，家祭无忘告乃翁。',
  },
  {
    title: '水调歌头·明月几时有',
    dynasty: '宋',
    author: '苏轼',
    digest: '明月几时有？把酒问青天。',
  },
  {
    title: '虞美人·春花秋月何时了',
    dynasty: '五代',
    author: '李煜',
    digest: '问君能有几多愁？恰似一江春水向东流。',
  },
  {
    title: '凉州词',
    dynasty: '唐',
    author: '王翰',
    digest: '醉卧沙场君莫笑，古来征战几人回？',
  },
  {
    title: '贺新郎·甚矣吾衰矣',
    dynasty: '宋',
    author: '辛弃疾',
    digest: '我见青山多妩媚，料青山见我应如是。',
  },
  {
    title: '小松',
    dynasty: '唐',
    author: '杜荀鹤',
    digest: '时人不识凌云木，直待凌云始道高。',
  },
  {
    title: '酬乐天咏老见示',
    dynasty: '唐',
    author: '刘禹锡',
    digest: '莫道桑榆晚，为霞尚满天。',
  },
  {
    title: '上堂开示颂',
    dynasty: '唐',
    author: '黄櫱禅师',
    digest: '不经一番寒彻骨，怎得梅花扑鼻香。',
  },
  {
    title: '赴戍登程口占示家人二首',
    dynasty: '清',
    author: '林则徐',
    digest: '苟利国家生死以，岂因祸福避趋之。',
  },
  {
    title: '荀子·大略',
    dynasty: '战国',
    author: '荀子',
    digest: '岁不寒无以知松柏，事不难无以知君子。',
  },
  {
    title: '劝学',
    dynasty: '唐',
    author: '颜真卿',
    digest: '三更灯火五更鸡，正是男儿读书时。',
  },
  {
    title: '七绝·呈父亲',
    dynasty: '近现代',
    author: '毛泽东',
    digest: '埋骨何须桑梓地，人生无处不青山。',
  },
  {
    title: '七绝·咏蛙',
    dynasty: '近现代',
    author: '毛泽东',
    digest: '春来我不先开口，哪个虫儿敢作声。',
  },
  {
    title: '渔家傲·反第一次大围剿',
    dynasty: '近现代',
    author: '毛泽东',
    digest: '唤起工农千百万，同心干，不周山下红旗乱。',
  },
  {
    title: '满江红·和郭沫若同志',
    dynasty: '近现代',
    author: '毛泽东',
    digest: '一万年太久，只争朝夕。',
  },
  {
    title: '七律·到韶山',
    dynasty: '近现代',
    author: '毛泽东',
    digest: '为有牺牲多壮志，敢教日月换新天。',
  },
  {
    title: '浪淘沙·北戴河',
    dynasty: '近现代',
    author: '毛泽东',
    digest: '萧瑟秋风今又是，换了人间。',
  },
  {
    title: '沁园春·雪',
    dynasty: '近现代',
    author: '毛泽东',
    digest: '俱往矣，数风流人物，还看今朝。',
  },
  {
    title: '临江王节士歌',
    dynasty: '唐',
    author: '李白',
    digest: '安得倚天剑，跨海斩长鲸。',
  },
  {
    title: '江城子·西城杨柳弄春柔',
    dynasty: '宋',
    author: '秦观',
    digest: '韶华不为少年留，恨悠悠，几时休。',
  },
  {
    title: '望江南·超然台作',
    dynasty: '宋',
    author: '苏轼',
    digest: '且将新火试新茶，诗酒趁年华。',
  },
  {
    title: '水调歌头·游览',
    dynasty: '宋',
    author: '黄庭坚',
    digest: '我欲穿花寻路，直入白云深处，浩气展虹霓。',
  },
  {
    title: '水调歌头·黄州快哉亭赠张偓佺',
    dynasty: '宋',
    author: '苏轼',
    digest: '一点浩然气，千里快哉风。',
  },
  {
    title: '献钱尚父',
    dynasty: '唐',
    author: '贯休',
    digest: '满堂花醉三千客，一剑霜寒十四州。',
  },
  {
    title: '登科后',
    dynasty: '唐',
    author: '孟郊',
    digest: '春风得意马蹄疾，一日看尽长安花。',
  },
  {
    title: '西江月·世事一场大梦',
    dynasty: '宋',
    author: '苏轼',
    digest: '世事一场大梦，人生几度秋凉。',
  },
  {
    title: '早发白帝城',
    dynasty: '唐',
    author: '李白',
    digest: '两岸猿声啼不住，轻舟已过万重山。',
  },
  {
    title: '望岳',
    dynasty: '唐',
    author: '杜甫',
    digest: '会当凌绝顶，一览众山小。',
  },
  {
    title: '出塞二首·其一',
    dynasty: '唐',
    author: '王昌龄',
    digest: '但使龙城飞将在，不教胡马度阴山。',
  },
  {
    title: '梅岭三章·其一',
    dynasty: '近现代',
    author: '陈毅',
    digest: '此去泉台招旧部，旌旗十万斩阎罗。',
  },
  {
    title: '宣州谢朓楼饯别校书叔云',
    dynasty: '唐',
    author: '李白',
    digest: '俱怀逸兴壮思飞，欲上青天揽明月。',
  },
  {
    title: '旅夜书怀',
    dynasty: '唐',
    author: '杜甫',
    digest: '星垂平野阔，月涌大江流。',
  },
  {
    title: '己亥杂诗·其二百二十',
    dynasty: '清',
    author: '龚自珍',
    digest: '我劝天公重抖擞，不拘一格降人才。',
  },
  {
    title: '鹧鸪天·桂花',
    dynasty: '宋',
    author: '李清照',
    digest: '何须浅碧轻红色，自是花中第一流。',
  },
  {
    title: '饮中八仙歌',
    dynasty: '唐',
    author: '杜甫',
    digest: '天子呼来不上船，自称臣是酒中仙。',
  },
  {
    title: '一剪梅·余赴广东实之夜饯于风亭',
    dynasty: '宋',
    author: '刘克庄',
    digest: '旁观拍手笑疏狂，疏又何妨，狂又何妨。',
  },
  {
    title: '望庐山瀑布',
    dynasty: '唐',
    author: '李白',
    digest: '飞流直下三千尺，疑是银河落九天。',
  },
  {
    title: '满江红·小住京华',
    dynasty: '清',
    author: '秋瑾',
    digest: '身不得，男儿列；心却比，男儿烈。',
  },
  {
    title: '破阵子·为陈同甫赋壮词以寄之',
    dynasty: '宋',
    author: '辛弃疾',
    digest: '了却君王天下事，赢得生前身后名。',
  },
  {
    title: '过零丁洋',
    dynasty: '宋',
    author: '文天祥',
    digest: '人生自古谁无死？留取丹心照汗青。',
  },
  {
    title: '自嘲',
    dynasty: '近现代',
    author: '鲁迅',
    digest: '横眉冷对千夫指，俯首甘为孺子牛。',
  },
  {
    title: '把酒问月·故人贾淳令予问之',
    dynasty: '唐',
    author: '李白',
    digest: '今人不见古时月，今月曾经照古人。',
  },
  {
    title: '老将行',
    dynasty: '唐',
    author: '王维',
    digest: '一身转战三千里，一剑曾当百万师。',
  },
  {
    title: '南园十三首·其五',
    dynasty: '唐',
    author: '李贺',
    digest: '男儿何不带吴钩，收取关山五十州。',
  },
  {
    title: '雁门太守行',
    dynasty: '唐',
    author: '李贺',
    digest: '报君黄金台上意，提携玉龙为君死。',
  },
  {
    title: '别董大二首',
    dynasty: '唐',
    author: '高适',
    digest: '莫愁前路无知己，天下谁人不识君。',
  },
  {
    title: '一剪梅·红藕香残玉簟秋',
    dynasty: '宋',
    author: '李清照',
    digest: '花自飘零水自流。一种相思，两处闲愁。',
  },
  {
    title: '西江月·夜行黄沙道中',
    dynasty: '宋',
    author: '辛弃疾',
    digest: '明月别枝惊鹊，清风半夜鸣蝉。',
  },
  {
    title: '永遇乐·京口北固亭怀古',
    dynasty: '宋',
    author: '辛弃疾',
    digest: '想当年，金戈铁马，气吞万里如虎。',
  },
  {
    title: '写情',
    dynasty: '唐',
    author: '李益',
    digest: '从此无心爱良夜，任他明月下西楼。',
  },
  {
    title: '寄黄几复',
    dynasty: '宋',
    author: '黄庭坚',
    digest: '桃李春风一杯酒，江湖夜雨十年灯。',
  },
  {
    title: '青青陵上柏',
    dynasty: '汉',
    author: '无名氏',
    digest: '人生天地间，忽如远行客。',
  },
  {
    title: '唐多令·芦叶满汀洲',
    dynasty: '宋',
    author: '刘过',
    digest: '欲买桂花同载酒，终不似，少年游。',
  },
  {
    title: '鹧鸪天·陌上柔桑破嫩芽',
    dynasty: '宋',
    author: '辛弃疾',
    digest: '若教眼底无离恨，不信人间有白头。',
  },
  {
    title: '摸鱼儿·雁丘词',
    dynasty: '金',
    author: '元好问',
    digest: '问世间情为何物？直教生死相许。',
  },
  {
    title: '木兰花·拟古决绝词柬友',
    dynasty: '清',
    author: '纳兰性德',
    digest: '人生若只如初见，何事秋风悲画扇。',
  },
  {
    title: '浣溪沙·一曲新词酒一杯',
    dynasty: '宋',
    author: '晏殊',
    digest: '无可奈何花落去，似曾相识燕归来。',
  },
  {
    title: '题都城南庄',
    dynasty: '唐',
    author: '崔护',
    digest: '人面不知何处去，桃花依旧笑春风。',
  },
  {
    title: '赠质上人',
    dynasty: '唐',
    author: '杜荀鹤',
    digest: '逢人不说人间事，便是人间无事人。',
  },
  {
    title: '别子才司令',
    dynasty: '宋',
    author: '方岳',
    digest: '不如意事常八九，可与语人无二三。',
  },
  {
    title: '题龙阳县青草湖',
    dynasty: '元',
    author: '唐温如',
    digest: '醉后不知天在水，满船清梦压星河。',
  },
  {
    title: '锦瑟',
    dynasty: '唐',
    author: '李商隐',
    digest: '此情可待成追忆，只是当时已惘然。',
  },
  {
    title: '送柴侍御',
    dynasty: '唐',
    author: '王昌龄',
    digest: '青山一道同云雨，明月何曾是两乡。',
  },
  {
    title: '自题金山画像',
    dynasty: '宋',
    author: '苏轼',
    digest: '心似已灰之木，身如不系之舟。',
  },
  {
    title: '和子由渑池怀旧',
    dynasty: '宋',
    author: '苏轼',
    digest: '人生到处知何似，应似飞鸿踏雪泥。',
  },
  {
    title: '杂诗七首·其一',
    dynasty: '宋',
    author: '黄庭坚',
    digest: '毕竟几人真得鹿，不知终日梦为鱼。',
  },
  {
    title: '赠妓云英',
    dynasty: '唐',
    author: '罗隐',
    digest: '我未成名卿未嫁，可能俱是不如人。',
  },
  {
    title: '送杜少府之任蜀州',
    dynasty: '唐',
    author: '王勃',
    digest: '海内存知己，天涯若比邻。',
  },
  {
    title: '满江红·写怀',
    dynasty: '宋',
    author: '岳飞',
    digest: '莫等闲，白了少年头，空悲切！',
  },
  {
    title: '无题·昨夜星辰昨夜风',
    dynasty: '唐',
    author: '李商隐',
    digest: '身无彩凤双飞翼，心有灵犀一点通。',
  },
  {
    title: '琵琶行',
    dynasty: '唐',
    author: '白居易',
    digest: '同是天涯沦落人，相逢何必曾相识。',
  },
  {
    title: '渡汉江',
    dynasty: '唐',
    author: '宋之问',
    digest: '近乡情更怯，不敢问来人。',
  },
  {
    title: '问刘十九',
    dynasty: '唐',
    author: '白居易',
    digest: '晚来天欲雪，能饮一杯无？',
  },
  {
    title: '鹊桥仙·纤云弄巧',
    dynasty: '宋',
    author: '秦观',
    digest: '两情若是久长时，又岂在朝朝暮暮？',
  },
  {
    title: '离思五首·其四',
    dynasty: '唐',
    author: '元稹',
    digest: '曾经沧海难为水，除却巫山不是云。',
  },
  {
    title: '木兰花·拟古决绝词柬友',
    dynasty: '清',
    author: '纳兰性德',
    digest: '等闲变却故人心，却道故人心易变。',
  },
  {
    title: '临江仙·滚滚长江东逝水',
    dynasty: '明',
    author: '杨慎',
    digest: '青山依旧在，几度夕阳红。',
  },
  {
    title: '观书有感·其一',
    dynasty: '宋',
    author: '朱熹',
    digest: '问渠那得清如许？为有源头活水来。',
  },
  {
    title: '武陵春·春晚',
    dynasty: '宋',
    author: '李清照',
    digest: '物是人非事事休，欲语泪先流。',
  },
  {
    title: '一剪梅·雨打梨花深闭门',
    dynasty: '明',
    author: '唐寅',
    digest: '晓看天色暮看云，行也思君，坐也思君。',
  },
  {
    title: '无题·相见时难别亦难',
    dynasty: '唐',
    author: '李商隐',
    digest: '春蚕到死丝方尽，蜡炬成灰泪始干。',
  },
  {
    title: '己亥杂诗·其五',
    dynasty: '清',
    author: '龚自珍',
    digest: '落红不是无情物，化作春泥更护花。',
  },
  {
    title: '雪梅·其一',
    dynasty: '宋',
    author: '卢梅坡',
    digest: '梅须逊雪三分白，雪却输梅一段香。',
  },
  {
    title: '白雪歌送武判官归京',
    dynasty: '唐',
    author: '岑参',
    digest: '忽如一夜春风来，千树万树梨花开。',
  },
  {
    title: '卜算子·咏梅',
    dynasty: '宋',
    author: '陆游',
    digest: '零落成泥碾作尘，只有香如故。',
  },
  {
    title: '酬乐天扬州初逢席上见赠',
    dynasty: '唐',
    author: '刘禹锡',
    digest: '沉舟侧畔千帆过，病树前头万木春。',
  },
  {
    title: '寄李十二白二十韵',
    dynasty: '唐',
    author: '杜甫',
    digest: '笔落惊风雨，诗成泣鬼神。',
  },
  {
    title: '清平乐·金风细细',
    dynasty: '宋',
    author: '晏殊',
    digest: '绿酒初尝人易醉。一枕小窗浓睡。',
  },
  {
    title: '题西林壁',
    dynasty: '宋',
    author: '苏轼',
    digest: '横看成岭侧成峰，远近高低各不同。',
  },
  {
    title: '观内怀仙',
    dynasty: '唐',
    author: '王勃',
    digest: '自能成羽翼，何必仰云梯。',
  },
  {
    title: '长相思·面苍然',
    dynasty: '宋',
    author: '陆游',
    digest: '画凌烟，上甘泉。自古功名属少年。',
  },
  {
    title: '出老',
    dynasty: '清',
    author: '林则徐',
    digest: '海到尽头天作岸，山登绝顶我为峰。',
  },
  {
    title: '出自蓟北门行',
    dynasty: '唐',
    author: '李白',
    digest: '挥刃斩楼兰，弯弓射贤王。',
  },
  {
    title: '贺新郎·同父见和再用韵答之',
    dynasty: '宋',
    author: '辛弃疾',
    digest: '男儿到死心如铁，看试手，补天裂。',
  },
  {
    title: '经乱离后天恩流夜郎忆旧游书怀赠江夏韦太守良宰',
    dynasty: '唐',
    author: '李白',
    digest: '仙人抚我顶，结发受长生。',
  },
  {
    title: '满江红·写怀',
    dynasty: '宋',
    author: '岳飞',
    digest: '待从头、收拾旧山河，朝天阙。',
  },
  {
    title: '江上吟',
    dynasty: '唐',
    author: '李白',
    digest: '兴酣落笔摇五岳，诗成笑傲凌沧洲。',
  },
  {
    title: '江城子·密州出猎',
    dynasty: '宋',
    author: '苏轼',
    digest: '会挽雕弓如满月，西北望，射天狼。',
  },
]
